# Generated by Django 4.1.1 on 2022-09-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Имя агента')),
                ('surname', models.CharField(max_length=75, verbose_name='Фамилия агента')),
                ('link_agent', models.CharField(blank=True, max_length=195, verbose_name='Ссылка')),
                ('agent_phone', models.CharField(max_length=12, verbose_name='Номер телефона Агента')),
                ('inviteAgent', models.IntegerField(null=True, verbose_name='Кто пригласил')),
                ('lenInvited', models.IntegerField(default=0, verbose_name='Количество приглашений')),
                ('manager_personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='managers.manager')),
            ],
            options={
                'verbose_name': 'Агента',
                'verbose_name_plural': 'Агенты',
            },
        ),
    ]
