# Generated by Django 4.1.1 on 2022-09-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Имя менеджера')),
                ('surname', models.CharField(max_length=75, verbose_name='Фамилия менеджера')),
                ('idFromBitrix', models.IntegerField(unique=True, verbose_name='ID в битриксе')),
                ('agents', models.IntegerField(default=0, verbose_name='Количество агентов')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
    ]
