# Generated by Django 4.0.2 on 2022-02-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShotrLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=21, verbose_name='ФИО агента')),
                ('initiator_agent', models.CharField(max_length=11, verbose_name='Номер телефона Инициатора')),
                ('initiator', models.CharField(max_length=25, verbose_name='Инициантор')),
            ],
        ),
    ]
