# Generated by Django 4.0.2 on 2022-02-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_rename_initiator_agent_shotrlinks_initiator_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotrlinks',
            name='link',
            field=models.CharField(max_length=195, unique=True, verbose_name='Ссылка'),
        ),
    ]
