# Generated by Django 4.0.2 on 2022-02-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_shotrlinks_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotrlinks',
            name='link',
            field=models.CharField(max_length=195, verbose_name='Ссылка'),
        ),
    ]
