# Generated by Django 4.0.2 on 2022-02-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_alter_shotrlinks_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotrlinks',
            name='agent',
            field=models.CharField(max_length=75, verbose_name='ФИО агента'),
        ),
        migrations.AlterField(
            model_name='shotrlinks',
            name='initiator',
            field=models.CharField(max_length=75, verbose_name='Инициантор'),
        ),
    ]
