# Generated by Django 4.0.2 on 2022-02-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_alter_shotrlinks_agent_alter_shotrlinks_initiator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotrlinks',
            name='initiator_phone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона Инициатора'),
        ),
    ]
