# Generated by Django 4.1 on 2022-08-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_agent_manager_agent_manager_personal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShotrLinks',
        ),
    ]
