# Generated by Django 4.1 on 2022-08-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0010_alter_agent_agent_phone_alter_agent_manager_personal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='agents',
            field=models.ManyToManyField(to='links.agent'),
        ),
    ]
