# Generated by Django 4.1 on 2022-08-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0012_remove_manager_agents_manager_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='agents',
            field=models.CharField(max_length=999, verbose_name='Количество агентов'),
        ),
    ]
