# Generated by Django 4.1 on 2022-08-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0013_alter_manager_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='agents',
            field=models.IntegerField(verbose_name='Количество агентов'),
        ),
    ]
