# Generated by Django 4.1.1 on 2022-09-10 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0014_alter_manager_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='manager_personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.manager'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='agents',
            field=models.IntegerField(null=True, verbose_name='Количество агентов'),
        ),
    ]
