# Generated by Django 4.1.1 on 2022-09-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0015_alter_agent_manager_personal_alter_manager_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='idFromBitrix',
            field=models.IntegerField(default=0, unique=True, verbose_name='ID в битриксе'),
            preserve_default=False,
        ),
    ]
